name: uji_kom_tsa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: 4.6.5
  firebase_core: 2.1.1
  firebase_auth: ^4.1.0
  google_sign_in: 5.4.2
  font_awesome_flutter: ^10.2.1
  geocoding: ^2.0.5
  platform: ^3.1.0
  geolocator: ^9.0.2
  android_intent_plus: ^3.1.5
  flutter: 
    sdk: flutter
  cloud_firestore: ^4.0.3
  uuid: ^3.0.6
  cloud_firestore_odm: ^1.0.0-dev.38
  json_annotation: ^4.7.0

dev_dependencies: 
  build_runner: ^2.3.2
  cloud_firestore_odm_generator: ^1.0.0-dev.38
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.5.4

flutter: 
  uses-material-design: true
  fonts:
    - family: CustomIconData
      fonts:
        - asset: assets/fonts/CustomIconData.ttf

